poses:
  # 目标位姿1
  place_pose1:
    position:
      x: 0
      y: -0.1994
      z: 0.408
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0

  place_pose2:
    position:
      x: 0.09
      y: -0.1994
      z: 0.408
    orientation:
      qx: 0
      qy: 1
      qz: 0.0
      qw: 0.0

  place_pose3:
    position:
      x: 0.108
      y: -0.1094
      z: 0.408
    orientation:
      qx: 0
      qy: 1
      qz: 0.0
      qw: 0.0

  pose1:
    position:
      x: 0
      y: -0.199
      z: 0.22
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0

  pose2:
    position:
      x: 0.09
      y: -0.199
      z: 0.22
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0

  pose3:
    position:
      x: 0.105
      y: -0.109
      z: 0.22
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0

obstacles:
  # 圆柱体障碍物
  cylinder1:
    type: cylinder
    dimensions:
      radius: 0.025  # 半径
      height: 0.070  # 高度
  cylinder2:
    type: cylinder
    dimensions:
      radius: 0.025  # 半径
      height: 0.070  # 高度
  cylinder3:
    type: cylinder
    dimensions:
      radius: 0.025  # 半径
      height: 0.070  # 高度
grasp_poses:
  grasp1:
    offset:
      x: 0.0
      y: 0.0
      z: 0.188
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0
  grasp2:
    offset:
      x: 0.0
      y: 0.0
      z: 0.185
    orientation:
      qx: 0.0
      qy: 1.0
      qz: 0.0
      qw: 0.0
